const rappers = [
  "Travis Scott",
  "Biggie",
  "Tupac",
  "Eminem",
  "Lil Pump",
  "Lil Flip",
  "Lil Wayne",
  "Drake",
  "Kanye West",
  "Jay Z",
  "ASAP ROCKY",
  "Rakim",
  "Ice Cube",
  "Eazy E",
  "Snoop Dogg",
  "XXX Tentacion",
  "Wifis Funeral",
  "Mac Miller",
  "Post Malone",
  "J Cole",
  "Kendrick Lamar",
  "Don Toliver",
  "Tekashi Six Nine",
  "Freddie Gibbs",
  "Tyler The Creator",
  "Cardi B",
  "Megan Thee Stallion",
  "Nicki Minaj",
  "Flo Milli",
  "Rick Ross",
  "Nas",
  "French Montana",
  "Gucci Mane",
  "T Pain",
  "Future",
  "Fifty Cent",
  "Ludacris",
  "SZA",
  "RZA",
  "Big Sean",
  "Dr Dre",
  "Kid Cudi",
  "Wiz Khalifa",
  "Lil Uzi Vert",
  "Lil Peep",
  "Trippie Redd",
  "Juice WRLD",
  "Pop Smoke",
  "Lil Yachty",
  "Smokepurpp",
]

export function getRapper(){
  return rappers[Math.floor(Math.random()*rappers.length)];
}